export const LOAD_CAMPAIGNS_SUCCESS = 'LOAD_CAMPAIGNS_SUCCESS';  
export const LOAD_CONTENT_SUCCESS = 'LOAD_CONTENT_SUCCESS';  
export const LOAD_AUDIENCE_SUCCESS = 'LOAD_AUDIENCE_SUCCESS';  
export const LOAD_LANGUAGES_SUCCESS = 'LOAD_LANGUAGES_SUCCESS';  
