export const FETCH_LANGUAGES = 'FETCH_LANGUAGES';
export const FETCH_LANGUAGES_DONE = 'FETCH_LANGUAGES_DONE';
export const FETCH_LANGUAGES_ERROR = 'FETCH_LANGUAGES_ERROR';
export const CREATE_LANGUAGE = 'CREATE_LANGUAGE';
export const CREATE_LANGUAGE_DONE = 'CREATE_LANGUAGE_DONE';
export const CREATE_LANGUAGE_ERROR = 'CREATE_LANGUAGE_ERROR';
